#!/usr/bin/env python3
"""
tools/ttf2lkfx.py — Convert TTF/OTF font thành file .c/.h cho lkfx

Yêu cầu:
    pip install Pillow

Cách dùng:
    python3 ttf2lkfx.py MyFont.ttf --size 16 --name my_font_16
    python3 ttf2lkfx.py MyFont.ttf --size 12 --size 16 --size 24

Output:
    my_font_16.c    ← thêm vào project
    my_font_16.h    ← include trong code

Trong code C:
    #include "my_font_16.h"
    lkfx_text(10, 20, "Hello!", &my_font_16, 1, LKFX_WHITE, LKFX_BLACK);

Ghi chú về hệ tọa độ:
    - Bitmap lưu theo ROW-MAJOR, MSB first (giống image2cpp)
    - Mỗi glyph có width riêng (proportional font)
    - Nếu muốn monospace: dùng --mono
"""

import sys
import os
import argparse
from PIL import Image, ImageDraw, ImageFont

def render_glyph(font_pil, char, size):
    """Render 1 ký tự, trả về (bitmap_bytes, width, height, x_advance)"""
    # Tạo canvas tạm để đo
    img = Image.new("L", (size*2, size*2), 0)
    draw = ImageDraw.Draw(img)

    # Đo bounding box
    bbox = font_pil.getbbox(char)
    if bbox is None:
        # Ký tự không có glyph (ví dụ space)
        x_advance = size // 3
        return bytes((size * x_advance + 7) // 8), x_advance, size, x_advance

    left, top, right, bottom = bbox
    gw = right - left
    gh = bottom - top
    if gw <= 0: gw = 1
    if gh <= 0: gh = size

    # Render vào canvas vừa đủ
    canvas = Image.new("L", (gw + 2, gh + 2), 0)
    dc = ImageDraw.Draw(canvas)
    dc.text((-left + 1, -top + 1), char, font=font_pil, fill=255)

    # Threshold → 1bpp
    pixels = canvas.load()
    cw, ch = canvas.size
    bitmap = []
    for row in range(ch):
        for col in range(cw):
            bitmap.append(1 if pixels[col, row] > 127 else 0)

    # Pack bits (MSB first, row-major)
    packed = bytearray()
    for i in range(0, len(bitmap), 8):
        byte = 0
        for b in range(8):
            if i + b < len(bitmap) and bitmap[i + b]:
                byte |= (1 << (7 - b))
        packed.append(byte)

    # x_advance: lấy từ font metrics
    try:
        adv = font_pil.getlength(char)
        x_advance = int(adv) + 1
    except Exception:
        x_advance = cw

    return bytes(packed), cw, ch, x_advance

def convert(ttf_path, sizes, name_prefix, first_char=32, last_char=127,
            mono=False, output_dir="."):
    try:
        from PIL import ImageFont as PILImageFont
    except ImportError:
        print("ERROR: Pillow not installed. Run: pip install Pillow")
        sys.exit(1)

    for size in sizes:
        font_name = f"{name_prefix}_{size}" if len(sizes) > 1 else name_prefix
        print(f"Converting {ttf_path} size={size} → {font_name}.c/.h")

        try:
            pil_font = ImageFont.truetype(ttf_path, size)
        except Exception as e:
            print(f"  ERROR loading font: {e}")
            continue

        bitmaps    = []
        glyphs     = []
        bitmap_off = 0
        max_h      = 0
        max_adv    = 0

        for code in range(first_char, last_char + 1):
            char = chr(code)
            bmp, gw, gh, adv = render_glyph(pil_font, char, size)
            glyphs.append({
                'offset':    bitmap_off,
                'width':     gw,
                'height':    gh,
                'x_advance': adv,
                'x_offset':  0,
                'y_offset':  0,
            })
            bitmaps.append(bmp)
            bitmap_off += len(bmp)
            if gh > max_h:  max_h  = gh
            if adv > max_adv: max_adv = adv

        if mono:
            # Monospace: tất cả cùng x_advance
            for g in glyphs:
                g['x_advance'] = max_adv

        # ── Tạo file .c ──
        c_path = os.path.join(output_dir, f"{font_name}.c")
        with open(c_path, "w") as f:
            f.write(f"/* Auto-generated by ttf2lkfx.py */\n")
            f.write(f"/* Source: {os.path.basename(ttf_path)}, size={size} */\n\n")
            f.write(f'#include "{font_name}.h"\n\n')

            # Bitmap
            f.write(f"static const uint8_t _bmp_{font_name}[] = {{\n")
            all_bytes = b"".join(bitmaps)
            for i, byte in enumerate(all_bytes):
                if i % 16 == 0: f.write("    ")
                f.write(f"0x{byte:02X},")
                if i % 16 == 15: f.write("\n")
            f.write("\n};\n\n")

            # Glyph table
            f.write(f"static const lkfx_glyph_t _glyph_{font_name}[{last_char - first_char + 1}] = {{\n")
            for i, g in enumerate(glyphs):
                f.write(f"    {{ {g['offset']:5d}, {g['width']:3d}, "
                        f"{g['height']:3d}, {g['x_advance']:3d}, "
                        f"{g['x_offset']:3d}, {g['y_offset']:3d} }},  "
                        f"/* {chr(first_char + i)!r} */\n")
            f.write("};\n\n")

            # Font struct
            f.write(f"const lkfx_font_t {font_name} = {{\n")
            f.write(f"    .bitmap     = _bmp_{font_name},\n")
            f.write(f"    .glyph      = _glyph_{font_name},\n")
            f.write(f"    .first_char = {first_char},\n")
            f.write(f"    .last_char  = {last_char},\n")
            f.write(f"    .height     = {max_h},\n")
            f.write(f"    .baseline   = {int(max_h * 0.8)},\n")
            f.write(f"}};\n")

        # ── Tạo file .h ──
        h_path = os.path.join(output_dir, f"{font_name}.h")
        guard  = font_name.upper() + "_H"
        with open(h_path, "w") as f:
            f.write(f"/* Auto-generated by ttf2lkfx.py */\n")
            f.write(f"#ifndef {guard}\n#define {guard}\n\n")
            f.write(f'#include "lkfx_font.h"\n\n')
            f.write(f"extern const lkfx_font_t {font_name};\n\n")
            f.write(f"#endif /* {guard} */\n")

        print(f"  → {c_path}")
        print(f"  → {h_path}")
        print(f"  Glyphs: {last_char - first_char + 1}, "
              f"Bitmap: {len(all_bytes)} bytes, Height: {max_h}px")

if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Convert TTF → lkfx C font")
    p.add_argument("ttf",          help="Đường dẫn file TTF/OTF")
    p.add_argument("--size",   "-s", type=int, action="append", default=[],
                   help="Cỡ pixel (có thể dùng nhiều lần: -s 12 -s 16 -s 24)")
    p.add_argument("--name",   "-n", default=None,
                   help="Tên biến C (mặc định: tên file không có extension)")
    p.add_argument("--mono",   action="store_true",
                   help="Monospace (tất cả ký tự cùng độ rộng)")
    p.add_argument("--first",  type=int, default=32,  help="ASCII đầu (mặc định 32)")
    p.add_argument("--last",   type=int, default=127, help="ASCII cuối (mặc định 127)")
    p.add_argument("--out",    "-o", default=".", help="Thư mục output")
    args = p.parse_args()

    if not args.size:
        args.size = [16]  # mặc định size 16

    name = args.name or os.path.splitext(os.path.basename(args.ttf))[0].lower()
    name = name.replace("-", "_").replace(" ", "_")

    convert(args.ttf, args.size, name,
            first_char=args.first, last_char=args.last,
            mono=args.mono, output_dir=args.out)
